/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as BaseImport } from "./app/_base"
import { Route as BaseIndexImport } from "./app/_base/index"
import { Route as BaseBlogPostsImport } from "./app/_base/blog/_posts"
import { Route as BaseBlogPostsIndexImport } from "./app/_base/blog/_posts.index"
import { Route as BaseBlogPostIdPostImport } from "./app/_base/blog/$postId/_post"
import { Route as BaseBlogPostIdPostIndexImport } from "./app/_base/blog/$postId/_post.index"

// Create Virtual Routes

const BaseBlogImport = createFileRoute("/_base/blog")()
const BaseBlogPostIdImport = createFileRoute("/_base/blog/$postId")()

// Create/Update Routes

const BaseRoute = BaseImport.update({
  id: "/_base",
  getParentRoute: () => rootRoute,
} as any)

const BaseBlogRoute = BaseBlogImport.update({
  path: "/blog",
  getParentRoute: () => BaseRoute,
} as any)

const BaseIndexRoute = BaseIndexImport.update({
  path: "/",
  getParentRoute: () => BaseRoute,
} as any)

const BaseBlogPostIdRoute = BaseBlogPostIdImport.update({
  path: "/$postId",
  getParentRoute: () => BaseBlogRoute,
} as any)

const BaseBlogPostsRoute = BaseBlogPostsImport.update({
  id: "/_posts",
  getParentRoute: () => BaseBlogRoute,
} as any)

const BaseBlogPostsIndexRoute = BaseBlogPostsIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogPostsRoute,
} as any)

const BaseBlogPostIdPostRoute = BaseBlogPostIdPostImport.update({
  id: "/_post",
  getParentRoute: () => BaseBlogPostIdRoute,
} as any)

const BaseBlogPostIdPostIndexRoute = BaseBlogPostIdPostIndexImport.update({
  path: "/",
  getParentRoute: () => BaseBlogPostIdPostRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_base": {
      id: "/_base"
      path: ""
      fullPath: ""
      preLoaderRoute: typeof BaseImport
      parentRoute: typeof rootRoute
    }
    "/_base/": {
      id: "/_base/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof BaseIndexImport
      parentRoute: typeof BaseImport
    }
    "/_base/blog": {
      id: "/_base/blog"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BaseBlogImport
      parentRoute: typeof BaseImport
    }
    "/_base/blog/_posts": {
      id: "/_base/blog/_posts"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BaseBlogPostsImport
      parentRoute: typeof BaseBlogRoute
    }
    "/_base/blog/$postId": {
      id: "/_base/blog/$postId"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BaseBlogPostIdImport
      parentRoute: typeof BaseBlogImport
    }
    "/_base/blog/$postId/_post": {
      id: "/_base/blog/$postId/_post"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BaseBlogPostIdPostImport
      parentRoute: typeof BaseBlogPostIdRoute
    }
    "/_base/blog/_posts/": {
      id: "/_base/blog/_posts/"
      path: "/"
      fullPath: "/blog/"
      preLoaderRoute: typeof BaseBlogPostsIndexImport
      parentRoute: typeof BaseBlogPostsImport
    }
    "/_base/blog/$postId/_post/": {
      id: "/_base/blog/$postId/_post/"
      path: "/"
      fullPath: "/blog/$postId/"
      preLoaderRoute: typeof BaseBlogPostIdPostIndexImport
      parentRoute: typeof BaseBlogPostIdPostImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  BaseRoute: BaseRoute.addChildren({
    BaseIndexRoute,
    BaseBlogRoute: BaseBlogRoute.addChildren({
      BaseBlogPostsRoute: BaseBlogPostsRoute.addChildren({
        BaseBlogPostsIndexRoute,
      }),
      BaseBlogPostIdRoute: BaseBlogPostIdRoute.addChildren({
        BaseBlogPostIdPostRoute: BaseBlogPostIdPostRoute.addChildren({
          BaseBlogPostIdPostIndexRoute,
        }),
      }),
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_base"
      ]
    },
    "/_base": {
      "filePath": "_base.tsx",
      "children": [
        "/_base/",
        "/_base/blog"
      ]
    },
    "/_base/": {
      "filePath": "_base/index.tsx",
      "parent": "/_base"
    },
    "/_base/blog": {
      "filePath": "_base/blog",
      "parent": "/_base",
      "children": [
        "/_base/blog/_posts",
        "/_base/blog/$postId"
      ]
    },
    "/_base/blog/_posts": {
      "filePath": "_base/blog/_posts.tsx",
      "parent": "/_base/blog",
      "children": [
        "/_base/blog/_posts/"
      ]
    },
    "/_base/blog/$postId": {
      "filePath": "_base/blog/$postId",
      "parent": "/_base/blog",
      "children": [
        "/_base/blog/$postId/_post"
      ]
    },
    "/_base/blog/$postId/_post": {
      "filePath": "_base/blog/$postId/_post.tsx",
      "parent": "/_base/blog/$postId",
      "children": [
        "/_base/blog/$postId/_post/"
      ]
    },
    "/_base/blog/_posts/": {
      "filePath": "_base/blog/_posts.index.tsx",
      "parent": "/_base/blog/_posts"
    },
    "/_base/blog/$postId/_post/": {
      "filePath": "_base/blog/$postId/_post.index.tsx",
      "parent": "/_base/blog/$postId/_post"
    }
  }
}
ROUTE_MANIFEST_END */
