/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from "@tanstack/react-router"

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as RouteImport } from "./app/route"
import { Route as BlogPostsImport } from "./app/blog/_posts"
import { Route as BlogPostsIndexImport } from "./app/blog/_posts.index"
import { Route as BlogPostIdPostImport } from "./app/blog/$postId/_post"
import { Route as BlogPostIdPostIndexImport } from "./app/blog/$postId/_post.index"

// Create Virtual Routes

const BlogImport = createFileRoute("/blog")()
const BlogPostIdImport = createFileRoute("/blog/$postId")()

// Create/Update Routes

const BlogRoute = BlogImport.update({
  path: "/blog",
  getParentRoute: () => rootRoute,
} as any)

const RouteRoute = RouteImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any)

const BlogPostIdRoute = BlogPostIdImport.update({
  path: "/$postId",
  getParentRoute: () => BlogRoute,
} as any)

const BlogPostsRoute = BlogPostsImport.update({
  id: "/_posts",
  getParentRoute: () => BlogRoute,
} as any)

const BlogPostsIndexRoute = BlogPostsIndexImport.update({
  path: "/",
  getParentRoute: () => BlogPostsRoute,
} as any)

const BlogPostIdPostRoute = BlogPostIdPostImport.update({
  id: "/_post",
  getParentRoute: () => BlogPostIdRoute,
} as any)

const BlogPostIdPostIndexRoute = BlogPostIdPostIndexImport.update({
  path: "/",
  getParentRoute: () => BlogPostIdPostRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof RouteImport
      parentRoute: typeof rootRoute
    }
    "/blog": {
      id: "/blog"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BlogImport
      parentRoute: typeof rootRoute
    }
    "/blog/_posts": {
      id: "/blog/_posts"
      path: "/blog"
      fullPath: "/blog"
      preLoaderRoute: typeof BlogPostsImport
      parentRoute: typeof BlogRoute
    }
    "/blog/$postId": {
      id: "/blog/$postId"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BlogPostIdImport
      parentRoute: typeof BlogImport
    }
    "/blog/$postId/_post": {
      id: "/blog/$postId/_post"
      path: "/$postId"
      fullPath: "/blog/$postId"
      preLoaderRoute: typeof BlogPostIdPostImport
      parentRoute: typeof BlogPostIdRoute
    }
    "/blog/_posts/": {
      id: "/blog/_posts/"
      path: "/"
      fullPath: "/blog/"
      preLoaderRoute: typeof BlogPostsIndexImport
      parentRoute: typeof BlogPostsImport
    }
    "/blog/$postId/_post/": {
      id: "/blog/$postId/_post/"
      path: "/"
      fullPath: "/blog/$postId/"
      preLoaderRoute: typeof BlogPostIdPostIndexImport
      parentRoute: typeof BlogPostIdPostImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  RouteRoute,
  BlogRoute: BlogRoute.addChildren({
    BlogPostsRoute: BlogPostsRoute.addChildren({ BlogPostsIndexRoute }),
    BlogPostIdRoute: BlogPostIdRoute.addChildren({
      BlogPostIdPostRoute: BlogPostIdPostRoute.addChildren({
        BlogPostIdPostIndexRoute,
      }),
    }),
  }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/blog"
      ]
    },
    "/": {
      "filePath": "route.tsx"
    },
    "/blog": {
      "filePath": "blog",
      "children": [
        "/blog/_posts",
        "/blog/$postId"
      ]
    },
    "/blog/_posts": {
      "filePath": "blog/_posts.tsx",
      "parent": "/blog",
      "children": [
        "/blog/_posts/"
      ]
    },
    "/blog/$postId": {
      "filePath": "blog/$postId",
      "parent": "/blog",
      "children": [
        "/blog/$postId/_post"
      ]
    },
    "/blog/$postId/_post": {
      "filePath": "blog/$postId/_post.tsx",
      "parent": "/blog/$postId",
      "children": [
        "/blog/$postId/_post/"
      ]
    },
    "/blog/_posts/": {
      "filePath": "blog/_posts.index.tsx",
      "parent": "/blog/_posts"
    },
    "/blog/$postId/_post/": {
      "filePath": "blog/$postId/_post.index.tsx",
      "parent": "/blog/$postId/_post"
    }
  }
}
ROUTE_MANIFEST_END */
